#Problem Statement
> IEEE is organizing an event and has set up registration through two portals. The participant data received from the two sources is given to you in the form of two spreadsheets. Write a script to automatically combine the list of participants into a single spreadsheet, with columns for Participant Name, Team Name, Participant Type (leader/member), Participant Phone Number and Participant Email. Make sure to handle edge cases such as missing data appropriately.

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_excel('anon_data1.xlsx') #have this file in Files pls
df1.shape # (167,7)
df1.info()
#Inference - No missing values to handle here
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Team Name       167 non-null    object
 1   Leader Name     167 non-null    object
 2   Leader Email    167 non-null    object
 3   Leader Phone    167 non-null    int64
 4   Leader College  167 non-null    object
 5   Leader Year     167 non-null    int64
 6   Members         167 non-null    object
dtypes: int64(2), object(5)
memory usage: 9.3+ KB

,Team Name,Leader Name,Leader Email,Leader Phone,Leader College,Leader Year,Members
0,Quasi,Farhan Ramesh,farhanramesh@example.com,9378726098,JADAVPUR UNIVERSITY,1,"farhanramesh@example.com, samarthtella@example..."
1,Quod facilis,Emir Sankaran,emirsankaran@example.com,7142657970,Jadavpur University,4,emirsankaran@example.com
2,Culque deserunt,Aaryahi Sule,aaryahisule@example.com,5396756934,Jadavpur University,2,aaryahisule@example.com
3,Nesciunt,Riaan Dave,riaandave@example.com,918530403071,University of calcutta,2,"riaandave@example.com, vivaansathe@example.com..."
4,Architecto neque,Prerak Sant,preraksant@example.com,6732270572,Jadavpur University,4,"preraksant@example.com, siyajayaraman@example.com"

In [ ]:
df2 = pd.read_csv('anon_data2.csv') #have this file in Files pls
df2.shape # (102,15)
df2.info()
#Inference - Missing values only in redundant columns so we can ignore
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Team Id                   102 non-null    object
 1   Team Name                 102 non-null    object
 2   Candidate Type            102 non-null    object
 3   Candidate's Name          102 non-null    object
 4   Candidate's Email         102 non-null    object
 5   Candidate's Mobile        102 non-null    int64
 6   Candidate's Gender        102 non-null    object
 7   Country                   102 non-null    object
 8   Course Pursuing           95 non-null     object
 9   Course Stream             94 non-null     object
 10  Specialization            92 non-null     object
 11  Year Of Study             88 non-null     object
 12  Passing Out Year          99 non-null     float64
 13  Candidate's Organisation  102 non-null    object
 14  Registration Time         102 non-null    object
dtypes: float64(1), int64(1), object(13)
memory usage: 12.1+ KB

,Team Id,Team Name,Candidate Type,Candidate's Name,Candidate's Email,Candidate's Mobile,Candidate's Gender,Country,Course Pursuing,Course Stream,Specialization,Year Of Study,Passing Out Year,Candidate's Organisation,Registration Time
0,UT0V02H2,Quia eaque,team leader,Tiya Krishnamurthy,tiyakrishnamurthy@example.com,8421266071,M,India,Engineering,B.Tech/BE,Computer Science,First Year,2027.0,"Amity University (AU), Gwalior, Madhya Pradesh",2024-02-24 21:21:08
1,UQI949V6,Ab eius,team member,Krish Madan,krishmadan@example.com,4823927726,M,India,Engineering,B.Tech/BE,Computer Science,Third Year,2025.0,Sister Nivedita University (SNU),2024-02-24 22:04:56
2,UQI949V6,Ab eius,team member,Shlok Varughese,shlokvarughese@example.com,2196306734,M,India,Engineering,B.Tech/BE,Computer Science,First Year,2025.0,"Indian Institute of Technology (IIT), Patna",2024-02-24 22:04:56
3,UQI949V6,Ab eius,team leader,Aaryahi Gara,aaryahigara@example.com,9207423064,M,India,Engineering,B.Tech/BE,Computer Science,Third Year,2025.0,Sister Nivedita University (SNU),2024-02-24 22:03:42
4,U486J3FV,Illo impedit,team leader,Ahana Gokhale,ahanagokhale@example.com,5318661231,M,India,NaN,NaN,NaN,NaN,NaN,Ms Enterprise,2024-02-24 22:15:45

#Thought process [1]:
`(Ive mostly explained within each cell what does what, all you gotta do is run each cell and see the dataset slowly merging together!! To work with the file please do make a copy in your drive before proceeding ^_^) `

Goal: a combined spreadsheet of format (according to the problem statemnt)  
**Participant name | Team name | Participant type | Participant Phn no. | Participant Email**  
  
Redundant columns:  
*   Leader College (Can be organized using regex)
*   Leader Year (No changes needed)
*   Organization, Course, Stream, Specialization, Passing out Year
*   Registration time
*   Team ID

In [ ]:
df1 = df1.drop(columns=["Leader College", "Leader Year"], axis=1)

In [ ]:
df2 = df2.drop(columns=["Candidate's Gender", "Country", "Course Pursuing", "Course Stream", "Specialization","Year Of Study", "Passing Out Year", "Candidate's Organisation", "Registration Time", "Team Id"], axis=1)

In [ ]:
df1.head()

,Team Name,Leader Name,Leader Email,Leader Phone,Members
0,Quasi,Farhan Ramesh,farhanramesh@example.com,9378726098,"farhanramesh@example.com, samarthtella@example..."
1,Quod facilis,Emir Sankaran,emirsankaran@example.com,7142657970,emirsankaran@example.com
2,Culque deserunt,Aaryahi Sule,aaryahisule@example.com,5396756934,aaryahisule@example.com
3,Nesciunt,Riaan Dave,riaandave@example.com,918530403071,"riaandave@example.com, vivaansathe@example.com..."
4,Architecto neque,Prerak Sant,preraksant@example.com,6732270572,"preraksant@example.com, siyajayaraman@example.com"

In [ ]:
df2.head()

,Team Name,Candidate Type,Candidate's Name,Candidate's Email,Candidate's Mobile
0,Quia eaque,team leader,Tiya Krishnamurthy,tiyakrishnamurthy@example.com,8421266071
1,Ab eius,team member,Krish Madan,krishmadan@example.com,4823927726
2,Ab eius,team member,Shlok Varughese,shlokvarughese@example.com,2196306734
3,Ab eius,team leader,Aaryahi Gara,aaryahigara@example.com,9207423064
4,Illo impedit,team leader,Ahana Gokhale,ahanagokhale@example.com,5318661231

#Thought Process [2]:
Cleaning Phone numbers

In [ ]:
df1["Leader Phone"] #Zeros at front and + have disappeared it seems

0        9378726098
1        7142657970
2        5396756934
3      918530403071
4        6732270572
           ...
162    916772011569
163      5194068516
164        94401773
165      5707628016
166      9714008896
Name: Leader Phone, Length: 167, dtype: int64

In [ ]:
def valid(number):
    number = int(number)  # Ensure it's int
    if len(str(number))<=10: #India has 10 digit number, but keep <10 anyways cuz it might help later
        return number
    elif len(str(number))==12: #removing 91 from 91(10 digit number)
        return number%(10**10)
    else:
        return None
df1["Leader Phone"] = df1["Leader Phone"].apply(valid)

In [ ]:
less_than_ten = df1[df1["Leader Phone"].apply(lambda x: len(str(x)) < 10)]["Leader Phone"]
less_than_ten #20 people have input less than 10 digits in this sheet it seems

9      354371597
11     674571534
18     381717236
24     895524744
33      20086671
39     602419024
40     333558103
43     764975337
48     599620618
65     368310383
69     946098500
77     976709890
88     949544467
92     722214485
107    836705358
108    309828699
117    114642090
129    873216500
152    215064612
164     94401773
Name: Leader Phone, dtype: int64

In [ ]:
df2["Candidate's Mobile"] = df2["Candidate's Mobile"].apply(valid)

In [ ]:
less_than_ten = df2[df2["Candidate's Mobile"].apply(lambda x: len(str(x)) < 10)]["Candidate's Mobile"]
less_than_ten #9 people have input less than 10 digits in this sheet it seems

19     346861169
25     689379580
31     807677717
37      65557455
44     111625776
56      85011221
68     632445985
88     878999037
101    908778388
Name: Candidate's Mobile, dtype: int64

#Thought process [3]:
Understanding common teams and limitations of the dataset

In [ ]:
emails = list(df1['Members'])
numInEmails = list(map(lambda x: x.count(',')+1, emails))
sum(numInEmails) #336 emails/participants in df1

336

In [ ]:
df1_teams = set(df1["Team Name"].unique())
df2_teams = set(df2["Team Name"].unique())
common_teams = df1_teams & df2_teams

print(f"✅ Total common teams: {len(common_teams)}") # 2 teams filled in both portals
print(common_teams)

✅ Total common teams: 2
{'Ab eius', 'Consequuntur corporis'}

In [ ]:
df1_common = df1[df1["Team Name"].isin(common_teams)]
df1_common

,Team Name,Leader Name,Leader Email,Leader Phone,Members
91,Consequuntur corporis,Saira Sharma,sairasharma@example.com,8518779124,"sairasharma@example.com, amirasidhu@example.com"
138,Ab eius,Aaryahi Gara,aaryahigara@example.com,9207423064,"aaryahigara@example.com, shlokvarughese@exampl..."

In [ ]:
df2_common = df2[df2["Team Name"].isin(common_teams)]
df2_common

,Team Name,Candidate Type,Candidate's Name,Candidate's Email,Candidate's Mobile
1,Ab eius,team member,Krish Madan,krishmadan@example.com,4823927726
2,Ab eius,team member,Shlok Varughese,shlokvarughese@example.com,2196306734
3,Ab eius,team leader,Aaryahi Gara,aaryahigara@example.com,9207423064
15,Consequuntur corporis,team member,Amira Sidhu,amirasidhu@example.com,7097859778
16,Consequuntur corporis,team leader,Saira Sharma,sairasharma@example.com,8518779124

**Limitations**: need to compress df2 onto df1 as df2 is flatenned. This process will delete all team member's names leading to abhorent amount of missing name values, while keeping their mobile no.s and emails intact, as we cant just generate candidates name from member emails can we?  
This goes against our goal of Participant type being both members and leader, and participant name having both leader and member names, but ultimately gets our job donw.  
Maybe portal 1 can improve on its registration form to omit this problem all together (just a suggestion i'm giving)

In [ ]:
unique_teams_df1 = set(df1["Team Name"].unique())
print(f"Unique teams in df1: {len(unique_teams_df1)}")

unique_teams_df2 = set(df2["Team Name"].unique())
print(f"Unique teams in df2: {len(unique_teams_df2)}")

common_teams = unique_teams_df1 & unique_teams_df2
print(f"Teams common to both: {len(common_teams)}")

expected_teams = unique_teams_df1.union(unique_teams_df2 - common_teams)
print(f"Expected total unique teams after merge: {len(expected_teams)}")

#Before merging just checking here how many should we expect in the final merged dataset (d1+d2-common)

Unique teams in df1: 167
Unique teams in df2: 85
Teams common to both: 2
Expected total unique teams after merge: 250

In [ ]:
# Step 1: Get team name sets
df1_teams = set(df1["Team Name"].unique())
df2_teams = set(df2["Team Name"].unique())
common_teams = df1_teams & df2_teams
only_df2_teams = df2_teams - df1_teams  # the 83 extra teams

# Step 2: Process teams only in df2 (like we did for common ones)
df2_extra = df2[df2["Team Name"].isin(only_df2_teams)]

extra_rows = []

for team in only_df2_teams:
    team_df = df2_extra[df2_extra["Team Name"] == team]

    leader_row = team_df[team_df["Candidate Type"].str.lower() == "team leader"]
    if leader_row.empty:
        continue  # skip if no leader info

    leader_name = leader_row["Candidate's Name"].values[0]
    leader_email = leader_row["Candidate's Email"].values[0]
    leader_phone = int(leader_row["Candidate's Mobile"].values[0])

    member_rows = team_df[team_df["Candidate's Email"] != leader_email]
    member_emails = member_rows["Candidate's Email"].tolist()

    members_str = ", ".join([leader_email] + member_emails)

    extra_rows.append({
        "Team Name": team,
        "Leader Name": leader_name,
        "Leader Email": leader_email,
        "Leader Phone": leader_phone,
        "Members": members_str
    })

# Step 3: Convert and merge
df2_extra_teams_formatted = pd.DataFrame(extra_rows)

# Step 4: Merge with original df1
final_df = pd.concat([df1, df2_extra_teams_formatted], ignore_index=True)

#Finale

In [ ]:
print(f"Final merged shape: {final_df.shape}")
final_df.info() # No null values
final_df

Final merged shape: (250, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Team Name     250 non-null    object
 1   Leader Name   250 non-null    object
 2   Leader Email  250 non-null    object
 3   Leader Phone  250 non-null    int64
 4   Members       250 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.9+ KB

,Team Name,Leader Name,Leader Email,Leader Phone,Members
0,Quasi,Farhan Ramesh,farhanramesh@example.com,9378726098,"farhanramesh@example.com, samarthtella@example..."
1,Quod facilis,Emir Sankaran,emirsankaran@example.com,7142657970,emirsankaran@example.com
2,Culque deserunt,Aaryahi Sule,aaryahisule@example.com,5396756934,aaryahisule@example.com
3,Nesciunt,Riaan Dave,riaandave@example.com,8530403071,"riaandave@example.com, vivaansathe@example.com..."
4,Architecto neque,Prerak Sant,preraksant@example.com,6732270572,"preraksant@example.com, siyajayaraman@example.com"
...,...,...,...,...,...
245,Veniam distinctio,Vedika Borde,vedikaborde@example.com,5131535796,vedikaborde@example.com
246,Sint eveniet,Biju Dada,bijudada@example.com,3206760019,bijudada@example.com
247,Eaque similique,Heer Lanka,heerlanka@example.com,85011221,heerlanka@example.com
248,Autem,Pranay Yogi,pranayyogi@example.com,4611162072,pranayyogi@example.com
249,Labore aliquid,Eshani Kunda,eshanikunda@example.com,8716251234,eshanikunda@example.com

In [ ]:
final_df.to_excel("merged_participants.xlsx", index=False)

**Next Steps?**- Some phone numbers are 8-9 digit, so we might want to pursue them via email to confirm/change number of Team leader